console.log('hello, world');
var h1 = document.querySelector('h1');
console.log(h1);
console.dir(h1);
var explanationId = document.querySelector('#explanation');
console.log(explanationId);
console.dir(explanationId);
var hintClass = document.querySelector('.hint');
console.log(hintClass);
console.dir(hintClass);
var p = document.querySelectorAll('p');
console.log(p);
var exampleLink = document.querySelectorAll('.example-link');
console.log(exampleLink);
